### PR TITLE
catch exceptions and notify before re-throwing

### LINKED ISSUE #2: only notifies on success
I recently created [my first boot project](https://github.com/parenthesis/isomorphiclj/blob/1f6cc24c737378a94cfea16d69ab71461c677dba/build.boot#L48-49) and am using `speak`/`notify` to alert me of test results. `speak` works on both success and failure, but `notify` only works on success.

### PR DESCRIPTION
**Pull request by domkm**
fixes #2

### CODE REVIEW

File: src/jeluard/boot_notify.clj [hunk 1]
```diff
@@ -51,22 +51,18 @@
...
-            (catch Throwable t
-              (when-let [s (:failure messages)]
-                (notify! n s base-message))
-              (throw t))))
+        (fn [next-task]
+          (fn [fileset]
+            (try
+              (util/with-let [_ (next-task fileset)]
+                (if (zero? @core/*warnings*)
+                  (notify! n (:success messages) base-message)
```
Comment (jeluard) [inline src/jeluard/boot_notify.clj:62]: One thing we lost here is the ability to disable notifications by specifying a nil template per message type. Would you mind restoring it, maybe in the `notify!` function?

Comment (domkm) [inline src/jeluard/boot_notify.clj:62]: @jeluard I thought the [type signature of that option](https://github.com/jeluard/boot-notify/blob/d779c5f961b7f5037342d0fb16cb279be4e0a8d4/src/jeluard/boot_notify.clj#L47) prevents non-string values.

``` clojure
(notify :template {:success nil})
;=> java.lang.IllegalArgumentException: option :template must be of type {kw str}
```

Comment (jeluard) [inline src/jeluard/boot_notify.clj:62]: Hmm ok. Never mind that can be relaxed later then.
